CREATE TABLE IF NOT EXISTS `zb_recurring_bills` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `org_id` varchar(100) NOT NULL,
  `zoho_recurring_bill_id` varchar(100) NOT NULL,
  `recurrence_name` varchar(255) DEFAULT NULL,
  `reference_number` varchar(100) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `zoho_vendor_id` varchar(100) DEFAULT NULL,
  `vendor_name` varchar(255) DEFAULT NULL,
  `recurrence_frequency` varchar(50) DEFAULT NULL,
  `repeat_every` int DEFAULT '1',
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `next_bill_date` date DEFAULT NULL,
  `last_sent_date` date DEFAULT NULL,
  `total` decimal(18,4) DEFAULT '0.0000',
  `sub_total` decimal(18,4) DEFAULT '0.0000',
  `tax_total` decimal(18,4) DEFAULT '0.0000',
  `currency_id` varchar(100) DEFAULT NULL,
  `currency_code` varchar(3) DEFAULT NULL,
  `exchange_rate` decimal(18,8) DEFAULT '1.00000000',
  `is_inclusive_tax` tinyint(1) DEFAULT '0',
  `zoho_created_time` datetime DEFAULT NULL,
  `zoho_last_modified_time` datetime DEFAULT NULL,
  `synced_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `raw_payload_id` bigint DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_zb_rbill` (`user_id`,`org_id`,`zoho_recurring_bill_id`),
  CONSTRAINT `zb_recurring_bills_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
