-- ─────────────────────────────────────────────────────────────────────────────
-- Zoho Books Warehouse migration — Foundation (Phases 0-5)
-- Idempotent: safe to re-run. Creates 45 tables prefixed zb_*.
-- Existing tables are NEVER touched.
-- ─────────────────────────────────────────────────────────────────────────────

-- ════════════════════════════════════════════════════════════════════════════
--  BRONZE — raw payload archive
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS zb_raw_payloads (
  id              BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id         INT          NOT NULL,
  org_id          VARCHAR(100) NULL,
  endpoint        VARCHAR(255) NOT NULL,
  method          VARCHAR(10)  DEFAULT 'GET',
  request_params  JSON         NULL,
  response_status INT          NULL,
  response_body   LONGTEXT     NULL,
  response_size   INT          NULL,
  page            INT          NULL,
  per_page        INT          NULL,
  fetched_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  duration_ms     INT          NULL,
  sync_run_id     BIGINT       NULL,
  error           TEXT         NULL,
  INDEX idx_raw_endpoint (endpoint),
  INDEX idx_raw_user_org (user_id, org_id),
  INDEX idx_raw_run      (sync_run_id),
  INDEX idx_raw_fetched  (fetched_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ════════════════════════════════════════════════════════════════════════════
--  AUDIT — sync run log
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS zb_sync_runs (
  id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id             INT          NOT NULL,
  org_id              VARCHAR(100) NULL,
  run_type            VARCHAR(50)  NOT NULL,
  trigger_source      VARCHAR(50)  NULL,
  triggered_by_user   INT          NULL,
  started_at          DATETIME     NOT NULL,
  completed_at        DATETIME     NULL,
  status              VARCHAR(20)  DEFAULT 'running',
  modules_requested   JSON         NULL,
  modules_completed   JSON         NULL,
  api_calls_made      INT          DEFAULT 0,
  records_inserted    INT          DEFAULT 0,
  records_updated     INT          DEFAULT 0,
  records_failed      INT          DEFAULT 0,
  error_summary       TEXT         NULL,
  last_modified_after DATETIME     NULL,
  INDEX idx_srun_user_org (user_id, org_id),
  INDEX idx_srun_status   (status),
  INDEX idx_srun_started  (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_sync_run_items (
  id              BIGINT AUTO_INCREMENT PRIMARY KEY,
  sync_run_id     BIGINT       NOT NULL,
  module          VARCHAR(50)  NOT NULL,
  endpoint        VARCHAR(255) NULL,
  started_at      DATETIME     NULL,
  completed_at    DATETIME     NULL,
  status          VARCHAR(20)  NULL,
  api_calls       INT          DEFAULT 0,
  records_fetched  INT         DEFAULT 0,
  records_inserted INT         DEFAULT 0,
  records_updated  INT         DEFAULT 0,
  records_failed   INT         DEFAULT 0,
  error           TEXT         NULL,
  raw_payload_id  BIGINT       NULL,
  INDEX idx_sruni_run    (sync_run_id),
  INDEX idx_sruni_module (module),
  FOREIGN KEY (sync_run_id) REFERENCES zb_sync_runs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_sync_watermarks (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  user_id             INT          NOT NULL,
  org_id              VARCHAR(100) NOT NULL,
  module              VARCHAR(50)  NOT NULL,
  last_modified_after DATETIME     NULL,
  last_synced_at      DATETIME     NULL,
  records_total       INT          DEFAULT 0,
  UNIQUE KEY uq_zb_watermark (user_id, org_id, module),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ════════════════════════════════════════════════════════════════════════════
--  SILVER — master data
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS zb_organizations (
  id                    INT AUTO_INCREMENT PRIMARY KEY,
  user_id               INT          NOT NULL,
  org_id                VARCHAR(100) NOT NULL,
  name                  VARCHAR(255) NULL,
  contact_name          VARCHAR(255) NULL,
  email                 VARCHAR(255) NULL,
  phone                 VARCHAR(50)  NULL,
  fax                   VARCHAR(50)  NULL,
  industry_type         VARCHAR(100) NULL,
  industry_size         VARCHAR(100) NULL,
  fiscal_year_start_month VARCHAR(20) NULL,
  language_code         VARCHAR(10)  NULL,
  date_format           VARCHAR(50)  NULL,
  field_separator       VARCHAR(10)  NULL,
  time_zone             VARCHAR(100) NULL,
  is_org_active         TINYINT(1)   DEFAULT 1,
  currency_id           VARCHAR(100) NULL,
  currency_code         VARCHAR(3)   NULL,
  currency_symbol       VARCHAR(10)  NULL,
  currency_format       VARCHAR(50)  NULL,
  price_precision       INT          DEFAULT 2,
  country               VARCHAR(100) NULL,
  state                 VARCHAR(100) NULL,
  city                  VARCHAR(100) NULL,
  street_address1       VARCHAR(255) NULL,
  street_address2       VARCHAR(255) NULL,
  zip                   VARCHAR(20)  NULL,
  org_address           TEXT         NULL,
  remit_to_address      TEXT         NULL,
  is_default_org        TINYINT(1)   DEFAULT 0,
  plan_type             INT          NULL,
  plan_name             VARCHAR(100) NULL,
  trial_expiry_date     DATE         NULL,
  is_trial_expired      TINYINT(1)   DEFAULT 0,
  tax_group_enabled     TINYINT(1)   DEFAULT 0,
  is_gst_registered     TINYINT(1)   DEFAULT 0,
  gst_no                VARCHAR(20)  NULL,
  tax_id                VARCHAR(100) NULL,
  source                VARCHAR(50)  NULL,
  custom_fields_json    JSON         NULL,
  zoho_created_time     DATETIME     NULL,
  zoho_last_modified_time DATETIME   NULL,
  synced_at             TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id        BIGINT       NULL,
  is_deleted            TINYINT(1)   DEFAULT 0,
  deleted_at            TIMESTAMP    NULL,
  UNIQUE KEY uq_zb_org (user_id, org_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_currencies (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  user_id           INT          NOT NULL,
  org_id            VARCHAR(100) NOT NULL,
  zoho_currency_id  VARCHAR(100) NOT NULL,
  currency_code     VARCHAR(3)   NOT NULL,
  currency_name     VARCHAR(100) NULL,
  currency_symbol   VARCHAR(10)  NULL,
  price_precision   INT          DEFAULT 2,
  currency_format   VARCHAR(50)  NULL,
  is_base_currency  TINYINT(1)   DEFAULT 0,
  exchange_rate     DECIMAL(18,8) DEFAULT 1.0,
  effective_date    DATE         NULL,
  synced_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id    BIGINT       NULL,
  is_deleted        TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_currency (user_id, org_id, zoho_currency_id),
  INDEX idx_zbc_code (currency_code),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_chart_of_accounts (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_account_id             VARCHAR(100) NOT NULL,
  account_code                VARCHAR(64)  NULL,
  account_name                VARCHAR(255) NOT NULL,
  account_type                VARCHAR(64)  NULL,
  account_type_formatted      VARCHAR(255) NULL,
  account_subtype             VARCHAR(64)  NULL,
  parent_account_id           VARCHAR(100) NULL,
  description                 TEXT         NULL,
  currency_id                 VARCHAR(100) NULL,
  currency_code               VARCHAR(3)   NULL,
  is_active                   TINYINT(1)   DEFAULT 1,
  is_system_account           TINYINT(1)   DEFAULT 0,
  can_show_in_ze              TINYINT(1)   DEFAULT 0,
  can_delete                  TINYINT(1)   DEFAULT 1,
  is_default_account          TINYINT(1)   DEFAULT 0,
  include_in_vat_return       TINYINT(1)   DEFAULT 0,
  current_balance             DECIMAL(18,4) DEFAULT 0,
  current_balance_formatted   VARCHAR(50)  NULL,
  documents_count             INT          DEFAULT 0,
  has_transactions            TINYINT(1)   DEFAULT 0,
  custom_fields_json          JSON         NULL,
  zoho_created_time           DATETIME     NULL,
  zoho_last_modified_time     DATETIME     NULL,
  synced_at                   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id              BIGINT       NULL,
  is_deleted                  TINYINT(1)   DEFAULT 0,
  deleted_at                  TIMESTAMP    NULL,
  UNIQUE KEY uq_zb_coa (user_id, org_id, zoho_account_id),
  INDEX idx_zbcoa_type   (account_type),
  INDEX idx_zbcoa_parent (parent_account_id),
  INDEX idx_zbcoa_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_tax_authorities (
  id                       INT AUTO_INCREMENT PRIMARY KEY,
  user_id                  INT          NOT NULL,
  org_id                   VARCHAR(100) NOT NULL,
  zoho_tax_authority_id    VARCHAR(100) NOT NULL,
  tax_authority_name       VARCHAR(255) NULL,
  description              TEXT         NULL,
  synced_at                TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_zbta (user_id, org_id, zoho_tax_authority_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_tax_exemptions (
  id                       INT AUTO_INCREMENT PRIMARY KEY,
  user_id                  INT          NOT NULL,
  org_id                   VARCHAR(100) NOT NULL,
  zoho_tax_exemption_id    VARCHAR(100) NOT NULL,
  tax_exemption_code       VARCHAR(64)  NULL,
  description              TEXT         NULL,
  synced_at                TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_zbte (user_id, org_id, zoho_tax_exemption_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_tax_rates (
  id                        INT AUTO_INCREMENT PRIMARY KEY,
  user_id                   INT          NOT NULL,
  org_id                    VARCHAR(100) NOT NULL,
  zoho_tax_id               VARCHAR(100) NOT NULL,
  tax_name                  VARCHAR(255) NOT NULL,
  tax_percentage            DECIMAL(7,4) DEFAULT 0,
  tax_type                  VARCHAR(64)  NULL,
  tax_specification         VARCHAR(64)  NULL,
  output_tax_account_id     VARCHAR(100) NULL,
  input_tax_account_id      VARCHAR(100) NULL,
  zoho_tax_authority_id     VARCHAR(100) NULL,
  zoho_tax_exemption_id     VARCHAR(100) NULL,
  is_value_added            TINYINT(1)   DEFAULT 0,
  is_default_tax            TINYINT(1)   DEFAULT 0,
  is_editable               TINYINT(1)   DEFAULT 1,
  country_code              VARCHAR(10)  NULL,
  synced_at                 TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id            BIGINT       NULL,
  is_deleted                TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zbtax (user_id, org_id, zoho_tax_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_tax_group_taxes (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  user_id             INT          NOT NULL,
  org_id              VARCHAR(100) NOT NULL,
  zoho_tax_group_id   VARCHAR(100) NOT NULL,
  zoho_tax_id         VARCHAR(100) NOT NULL,
  display_order       INT          DEFAULT 0,
  UNIQUE KEY uq_zbtg (user_id, org_id, zoho_tax_group_id, zoho_tax_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_items (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_item_id                VARCHAR(100) NOT NULL,
  name                        VARCHAR(255) NULL,
  item_name                   VARCHAR(255) NULL,
  description                 TEXT         NULL,
  rate                        DECIMAL(18,4) DEFAULT 0,
  unit                        VARCHAR(50)  NULL,
  status                      VARCHAR(50)  NULL,
  source                      VARCHAR(50)  NULL,
  is_combo_product            TINYINT(1)   DEFAULT 0,
  is_linked_with_zohocrm      TINYINT(1)   DEFAULT 0,
  item_type                   VARCHAR(50)  NULL,
  product_type                VARCHAR(50)  NULL,
  has_attachment              TINYINT(1)   DEFAULT 0,
  is_taxable                  TINYINT(1)   DEFAULT 1,
  tax_id                      VARCHAR(100) NULL,
  tax_name                    VARCHAR(255) NULL,
  tax_percentage              DECIMAL(7,4) NULL,
  tax_type                    VARCHAR(64)  NULL,
  account_id                  VARCHAR(100) NULL,
  account_name                VARCHAR(255) NULL,
  purchase_account_id         VARCHAR(100) NULL,
  purchase_account_name       VARCHAR(255) NULL,
  inventory_account_id        VARCHAR(100) NULL,
  purchase_description        TEXT         NULL,
  purchase_rate               DECIMAL(18,4) DEFAULT 0,
  vendor_id                   VARCHAR(100) NULL,
  vendor_name                 VARCHAR(255) NULL,
  reorder_level               DECIMAL(18,4) DEFAULT 0,
  initial_stock               DECIMAL(18,4) DEFAULT 0,
  initial_stock_rate          DECIMAL(18,4) DEFAULT 0,
  total_initial_stock         DECIMAL(18,4) DEFAULT 0,
  stock_on_hand               DECIMAL(18,4) DEFAULT 0,
  available_stock             DECIMAL(18,4) DEFAULT 0,
  actual_available_stock      DECIMAL(18,4) DEFAULT 0,
  sku                         VARCHAR(100) NULL,
  upc                         VARCHAR(100) NULL,
  ean                         VARCHAR(100) NULL,
  isbn                        VARCHAR(100) NULL,
  part_number                 VARCHAR(100) NULL,
  hsn_or_sac                  VARCHAR(50)  NULL,
  sat_item_key_code           VARCHAR(64)  NULL,
  unitkey_code                VARCHAR(64)  NULL,
  brand                       VARCHAR(100) NULL,
  manufacturer                VARCHAR(255) NULL,
  weight                      DECIMAL(18,4) NULL,
  weight_unit                 VARCHAR(20)  NULL,
  dimensions                  VARCHAR(100) NULL,
  dimension_unit              VARCHAR(20)  NULL,
  image_name                  VARCHAR(255) NULL,
  image_type                  VARCHAR(50)  NULL,
  custom_fields_json          JSON         NULL,
  zoho_created_time           DATETIME     NULL,
  zoho_last_modified_time     DATETIME     NULL,
  synced_at                   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id              BIGINT       NULL,
  is_deleted                  TINYINT(1)   DEFAULT 0,
  deleted_at                  TIMESTAMP    NULL,
  UNIQUE KEY uq_zb_item (user_id, org_id, zoho_item_id),
  INDEX idx_zbi_sku  (sku),
  INDEX idx_zbi_type (item_type),
  INDEX idx_zbi_mod  (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ════════════════════════════════════════════════════════════════════════════
--  SILVER — contacts, projects
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS zb_contacts (
  id                                  INT AUTO_INCREMENT PRIMARY KEY,
  user_id                             INT          NOT NULL,
  org_id                              VARCHAR(100) NOT NULL,
  zoho_contact_id                     VARCHAR(100) NOT NULL,
  contact_name                        VARCHAR(255) NULL,
  company_name                        VARCHAR(255) NULL,
  contact_type                        VARCHAR(50)  NULL,
  customer_sub_type                   VARCHAR(50)  NULL,
  status                              VARCHAR(50)  NULL,
  source                              VARCHAR(50)  NULL,
  is_linked_with_zohocrm              TINYINT(1)   DEFAULT 0,
  zohocrm_contact_id                  VARCHAR(100) NULL,
  outstanding_receivable_amount       DECIMAL(18,4) DEFAULT 0,
  outstanding_receivable_amount_bcy   DECIMAL(18,4) DEFAULT 0,
  unused_credits_receivable_amount    DECIMAL(18,4) DEFAULT 0,
  unused_credits_receivable_amount_bcy DECIMAL(18,4) DEFAULT 0,
  outstanding_payable_amount          DECIMAL(18,4) DEFAULT 0,
  outstanding_payable_amount_bcy      DECIMAL(18,4) DEFAULT 0,
  unused_credits_payable_amount       DECIMAL(18,4) DEFAULT 0,
  unused_credits_payable_amount_bcy   DECIMAL(18,4) DEFAULT 0,
  currency_id                         VARCHAR(100) NULL,
  currency_code                       VARCHAR(3)   NULL,
  currency_symbol                     VARCHAR(10)  NULL,
  exchange_rate                       DECIMAL(18,8) DEFAULT 1.0,
  tax_id                              VARCHAR(100) NULL,
  tax_name                            VARCHAR(255) NULL,
  tax_percentage                      DECIMAL(7,4) NULL,
  tax_authority_id                    VARCHAR(100) NULL,
  tax_authority_name                  VARCHAR(255) NULL,
  tax_exemption_id                    VARCHAR(100) NULL,
  tax_exemption_code                  VARCHAR(64)  NULL,
  tax_treatment                       VARCHAR(64)  NULL,
  gst_no                              VARCHAR(20)  NULL,
  gst_treatment                       VARCHAR(50)  NULL,
  place_of_contact                    VARCHAR(100) NULL,
  vat_reg_no                          VARCHAR(50)  NULL,
  vat_treatment                       VARCHAR(50)  NULL,
  payment_terms                       INT          DEFAULT 0,
  payment_terms_label                 VARCHAR(64)  NULL,
  credit_limit                        DECIMAL(18,4) DEFAULT 0,
  pricebook_id                        VARCHAR(100) NULL,
  pricebook_name                      VARCHAR(255) NULL,
  default_templates_json              JSON         NULL,
  notes                               TEXT         NULL,
  customer_currency_summary_json      JSON         NULL,
  primary_contact_id                  VARCHAR(100) NULL,
  language_code                       VARCHAR(10)  NULL,
  language_code_formatted             VARCHAR(64)  NULL,
  facebook                            VARCHAR(255) NULL,
  twitter                             VARCHAR(255) NULL,
  custom_fields_json                  JSON         NULL,
  zoho_created_time                   DATETIME     NULL,
  zoho_last_modified_time             DATETIME     NULL,
  synced_at                           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                      BIGINT       NULL,
  is_deleted                          TINYINT(1)   DEFAULT 0,
  deleted_at                          TIMESTAMP    NULL,
  UNIQUE KEY uq_zb_contact (user_id, org_id, zoho_contact_id),
  INDEX idx_zbc_type   (contact_type),
  INDEX idx_zbc_status (status),
  INDEX idx_zbc_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_contact_persons (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_contact_person_id      VARCHAR(100) NOT NULL,
  zoho_contact_id             VARCHAR(100) NOT NULL,
  salutation                  VARCHAR(20)  NULL,
  first_name                  VARCHAR(100) NULL,
  last_name                   VARCHAR(100) NULL,
  email                       VARCHAR(255) NULL,
  phone                       VARCHAR(50)  NULL,
  mobile                      VARCHAR(50)  NULL,
  skype                       VARCHAR(100) NULL,
  designation                 VARCHAR(100) NULL,
  department                  VARCHAR(100) NULL,
  is_primary_contact          TINYINT(1)   DEFAULT 0,
  is_added_in_portal          TINYINT(1)   DEFAULT 0,
  synced_at                   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_zb_cperson (user_id, org_id, zoho_contact_person_id),
  INDEX idx_zbcp_contact (zoho_contact_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_contact_addresses (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  user_id             INT          NOT NULL,
  org_id              VARCHAR(100) NOT NULL,
  zoho_address_id     VARCHAR(100) NULL,
  zoho_contact_id     VARCHAR(100) NOT NULL,
  address_type        VARCHAR(20)  NOT NULL,
  attention           VARCHAR(255) NULL,
  address             VARCHAR(255) NULL,
  street2             VARCHAR(255) NULL,
  city                VARCHAR(100) NULL,
  state               VARCHAR(100) NULL,
  state_code          VARCHAR(20)  NULL,
  zip                 VARCHAR(20)  NULL,
  country             VARCHAR(100) NULL,
  country_code        VARCHAR(10)  NULL,
  fax                 VARCHAR(50)  NULL,
  phone               VARCHAR(50)  NULL,
  synced_at           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_zbca_contact (zoho_contact_id, address_type),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_projects (
  id                      INT AUTO_INCREMENT PRIMARY KEY,
  user_id                 INT          NOT NULL,
  org_id                  VARCHAR(100) NOT NULL,
  zoho_project_id         VARCHAR(100) NOT NULL,
  project_name            VARCHAR(255) NULL,
  customer_id             VARCHAR(100) NULL,
  customer_name           VARCHAR(255) NULL,
  status                  VARCHAR(50)  NULL,
  description             TEXT         NULL,
  billing_type            VARCHAR(50)  NULL,
  rate                    DECIMAL(18,4) DEFAULT 0,
  budget_type             VARCHAR(50)  NULL,
  budget_hours            DECIMAL(18,4) NULL,
  budget_amount           DECIMAL(18,4) NULL,
  total_hours             DECIMAL(18,4) DEFAULT 0,
  billed_hours            DECIMAL(18,4) DEFAULT 0,
  un_billed_hours         DECIMAL(18,4) DEFAULT 0,
  currency_id             VARCHAR(100) NULL,
  currency_code           VARCHAR(3)   NULL,
  custom_fields_json      JSON         NULL,
  zoho_created_time       DATETIME     NULL,
  zoho_last_modified_time DATETIME     NULL,
  synced_at               TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id          BIGINT       NULL,
  is_deleted              TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_project (user_id, org_id, zoho_project_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_tasks (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  user_id             INT          NOT NULL,
  org_id              VARCHAR(100) NOT NULL,
  zoho_task_id        VARCHAR(100) NOT NULL,
  zoho_project_id     VARCHAR(100) NOT NULL,
  task_name           VARCHAR(255) NULL,
  description         TEXT         NULL,
  rate                DECIMAL(18,4) DEFAULT 0,
  budget_hours        DECIMAL(18,4) NULL,
  total_hours         DECIMAL(18,4) DEFAULT 0,
  billed_hours        DECIMAL(18,4) DEFAULT 0,
  un_billed_hours     DECIMAL(18,4) DEFAULT 0,
  synced_at           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_zb_task (user_id, org_id, zoho_task_id),
  INDEX idx_zbt_project (zoho_project_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_time_entries (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_time_entry_id          VARCHAR(100) NOT NULL,
  zoho_project_id             VARCHAR(100) NOT NULL,
  zoho_task_id                VARCHAR(100) NULL,
  user_zoho_id                VARCHAR(100) NULL,
  user_name                   VARCHAR(255) NULL,
  project_name                VARCHAR(255) NULL,
  task_name                   VARCHAR(255) NULL,
  customer_id                 VARCHAR(100) NULL,
  customer_name               VARCHAR(255) NULL,
  log_date                    DATE         NULL,
  begin_time                  TIME         NULL,
  end_time                    TIME         NULL,
  log_time                    VARCHAR(20)  NULL,
  hours                       DECIMAL(8,4) DEFAULT 0,
  is_billable                 TINYINT(1)   DEFAULT 1,
  billed_status               VARCHAR(50)  NULL,
  zoho_invoice_id             VARCHAR(100) NULL,
  invoice_status              VARCHAR(50)  NULL,
  notes                       TEXT         NULL,
  zoho_created_time           DATETIME     NULL,
  zoho_last_modified_time     DATETIME     NULL,
  synced_at                   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id              BIGINT       NULL,
  is_deleted                  TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_time (user_id, org_id, zoho_time_entry_id),
  INDEX idx_zbte_pt (zoho_project_id, zoho_task_id),
  INDEX idx_zbte_inv (zoho_invoice_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ════════════════════════════════════════════════════════════════════════════
--  SILVER — sales-side documents (estimates, SO, DC, invoices)
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS zb_estimates (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_estimate_id                VARCHAR(100) NOT NULL,
  estimate_number                 VARCHAR(100) NULL,
  reference_number                VARCHAR(100) NULL,
  status                          VARCHAR(50)  NULL,
  zoho_customer_id                VARCHAR(100) NULL,
  customer_name                   VARCHAR(255) NULL,
  email                           VARCHAR(255) NULL,
  date                            DATE         NULL,
  expiry_date                     DATE         NULL,
  accepted_date                   DATE         NULL,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_total                       DECIMAL(18,4) DEFAULT 0,
  discount                        DECIMAL(18,4) DEFAULT 0,
  shipping_charge                 DECIMAL(18,4) DEFAULT 0,
  adjustment                      DECIMAL(18,4) DEFAULT 0,
  total                           DECIMAL(18,4) DEFAULT 0,
  total_bcy                       DECIMAL(18,4) DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  is_inclusive_tax                TINYINT(1)   DEFAULT 0,
  is_viewed_by_client             TINYINT(1)   DEFAULT 0,
  client_viewed_time              DATETIME     NULL,
  template_id                     VARCHAR(100) NULL,
  template_name                   VARCHAR(255) NULL,
  notes                           TEXT         NULL,
  terms                           TEXT         NULL,
  billing_address_json            JSON         NULL,
  shipping_address_json           JSON         NULL,
  documents_count                 INT          DEFAULT 0,
  invoice_id                      VARCHAR(100) NULL,
  salesperson_id                  VARCHAR(100) NULL,
  salesperson_name                VARCHAR(255) NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_est (user_id, org_id, zoho_estimate_id),
  INDEX idx_zbe_status (status),
  INDEX idx_zbe_cust   (zoho_customer_id),
  INDEX idx_zbe_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_sales_orders (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_salesorder_id              VARCHAR(100) NOT NULL,
  salesorder_number               VARCHAR(100) NULL,
  reference_number                VARCHAR(100) NULL,
  status                          VARCHAR(50)  NULL,
  order_status                    VARCHAR(50)  NULL,
  invoiced_status                 VARCHAR(50)  NULL,
  paid_status                     VARCHAR(50)  NULL,
  shipped_status                  VARCHAR(50)  NULL,
  zoho_customer_id                VARCHAR(100) NULL,
  customer_name                   VARCHAR(255) NULL,
  date                            DATE         NULL,
  shipment_date                   DATE         NULL,
  delivery_method                 VARCHAR(100) NULL,
  delivery_method_id              VARCHAR(100) NULL,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_total                       DECIMAL(18,4) DEFAULT 0,
  discount                        DECIMAL(18,4) DEFAULT 0,
  adjustment                      DECIMAL(18,4) DEFAULT 0,
  shipping_charge                 DECIMAL(18,4) DEFAULT 0,
  total                           DECIMAL(18,4) DEFAULT 0,
  total_bcy                       DECIMAL(18,4) DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  is_inclusive_tax                TINYINT(1)   DEFAULT 0,
  estimate_id                     VARCHAR(100) NULL,
  is_dropshipment                 TINYINT(1)   DEFAULT 0,
  is_backorder                    TINYINT(1)   DEFAULT 0,
  is_pre_gst                      TINYINT(1)   DEFAULT 0,
  gst_treatment                   VARCHAR(50)  NULL,
  place_of_supply                 VARCHAR(100) NULL,
  template_id                     VARCHAR(100) NULL,
  notes                           TEXT         NULL,
  terms                           TEXT         NULL,
  billing_address_json            JSON         NULL,
  shipping_address_json           JSON         NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_so (user_id, org_id, zoho_salesorder_id),
  INDEX idx_zbso_cust   (zoho_customer_id),
  INDEX idx_zbso_status (status),
  INDEX idx_zbso_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_invoices (
  id                                  INT AUTO_INCREMENT PRIMARY KEY,
  user_id                             INT          NOT NULL,
  org_id                              VARCHAR(100) NOT NULL,
  zoho_invoice_id                     VARCHAR(100) NOT NULL,
  invoice_number                      VARCHAR(100) NULL,
  reference_number                    VARCHAR(100) NULL,
  zoho_customer_id                    VARCHAR(100) NULL,
  customer_name                       VARCHAR(255) NULL,
  contact_persons_json                JSON         NULL,
  email                               VARCHAR(255) NULL,
  cc_email                            VARCHAR(255) NULL,
  status                              VARCHAR(50)  NULL,
  invoice_url                         TEXT         NULL,
  is_emailed                          TINYINT(1)   DEFAULT 0,
  reminders_sent                      INT          DEFAULT 0,
  last_reminder_sent_date             DATE         NULL,
  date                                DATE         NULL,
  due_date                            DATE         NULL,
  due_days                            INT          NULL,
  payment_terms                       INT          DEFAULT 0,
  payment_terms_label                 VARCHAR(64)  NULL,
  is_pre_gst                          TINYINT(1)   DEFAULT 0,
  payment_made                        DECIMAL(18,4) DEFAULT 0,
  payment_expected_date               DATE         NULL,
  last_payment_date                   DATE         NULL,
  currency_id                         VARCHAR(100) NULL,
  currency_code                       VARCHAR(3)   NULL,
  currency_symbol                     VARCHAR(10)  NULL,
  exchange_rate                       DECIMAL(18,8) DEFAULT 1.0,
  sub_total                           DECIMAL(18,4) DEFAULT 0,
  tax_total                           DECIMAL(18,4) DEFAULT 0,
  discount                            DECIMAL(18,4) DEFAULT 0,
  discount_amount                     DECIMAL(18,4) DEFAULT 0,
  discount_applied_on_amount          DECIMAL(18,4) DEFAULT 0,
  discount_type                       VARCHAR(20)  NULL,
  is_discount_before_tax              TINYINT(1)   DEFAULT 1,
  adjustment                          DECIMAL(18,4) DEFAULT 0,
  adjustment_description              VARCHAR(255) NULL,
  shipping_charge                     DECIMAL(18,4) DEFAULT 0,
  total                               DECIMAL(18,4) DEFAULT 0,
  balance                             DECIMAL(18,4) DEFAULT 0,
  write_off_amount                    DECIMAL(18,4) DEFAULT 0,
  credits_applied                     DECIMAL(18,4) DEFAULT 0,
  sub_total_bcy                       DECIMAL(18,4) DEFAULT 0,
  tax_total_bcy                       DECIMAL(18,4) DEFAULT 0,
  total_bcy                           DECIMAL(18,4) DEFAULT 0,
  balance_bcy                         DECIMAL(18,4) DEFAULT 0,
  tax_treatment                       VARCHAR(64)  NULL,
  is_inclusive_tax                    TINYINT(1)   DEFAULT 0,
  is_reverse_charge_applied           TINYINT(1)   DEFAULT 0,
  vat_treatment                       VARCHAR(50)  NULL,
  gst_treatment                       VARCHAR(50)  NULL,
  gst_no                              VARCHAR(20)  NULL,
  place_of_supply                     VARCHAR(100) NULL,
  salesperson_id                      VARCHAR(100) NULL,
  salesperson_name                    VARCHAR(255) NULL,
  estimate_id                         VARCHAR(100) NULL,
  zoho_sales_order_id                 VARCHAR(100) NULL,
  recurring_invoice_id                VARCHAR(100) NULL,
  pricebook_id                        VARCHAR(100) NULL,
  template_id                         VARCHAR(100) NULL,
  template_name                       VARCHAR(255) NULL,
  shipping_charge_account_id          VARCHAR(100) NULL,
  shipping_charge_tax_id              VARCHAR(100) NULL,
  shipping_charge_tax_name            VARCHAR(100) NULL,
  shipping_charge_tax_percentage      DECIMAL(7,4) NULL,
  delivery_method                     VARCHAR(100) NULL,
  delivery_method_id                  VARCHAR(100) NULL,
  shipping_address_json               JSON         NULL,
  billing_address_json                JSON         NULL,
  notes                               TEXT         NULL,
  terms                               TEXT         NULL,
  payment_options_json                JSON         NULL,
  allow_partial_payments              TINYINT(1)   DEFAULT 0,
  custom_body                         TEXT         NULL,
  custom_subject                      TEXT         NULL,
  attachment_name                     VARCHAR(255) NULL,
  documents_count                     INT          DEFAULT 0,
  client_viewed_time                  DATETIME     NULL,
  approver_id                         VARCHAR(100) NULL,
  approver_name                       VARCHAR(255) NULL,
  current_sub_status                  VARCHAR(50)  NULL,
  color_code                          VARCHAR(20)  NULL,
  custom_fields_json                  JSON         NULL,
  zoho_created_time                   DATETIME     NULL,
  zoho_last_modified_time             DATETIME     NULL,
  synced_at                           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                      BIGINT       NULL,
  is_deleted                          TINYINT(1)   DEFAULT 0,
  deleted_at                          TIMESTAMP    NULL,
  UNIQUE KEY uq_zb_inv (user_id, org_id, zoho_invoice_id),
  INDEX idx_zbi_status (status),
  INDEX idx_zbi_cust   (zoho_customer_id),
  INDEX idx_zbi_date   (date),
  INDEX idx_zbi_due    (due_date),
  INDEX idx_zbi_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_invoice_line_items (
  id                                  INT AUTO_INCREMENT PRIMARY KEY,
  user_id                             INT          NOT NULL,
  org_id                              VARCHAR(100) NOT NULL,
  zoho_line_item_id                   VARCHAR(100) NOT NULL,
  zoho_invoice_id                     VARCHAR(100) NOT NULL,
  line_position                       INT          DEFAULT 0,
  zoho_item_id                        VARCHAR(100) NULL,
  item_name                           VARCHAR(255) NULL,
  description                         TEXT         NULL,
  name                                VARCHAR(255) NULL,
  product_type                        VARCHAR(50)  NULL,
  unit                                VARCHAR(50)  NULL,
  hsn_or_sac                          VARCHAR(50)  NULL,
  account_id                          VARCHAR(100) NULL,
  account_name                        VARCHAR(255) NULL,
  quantity                            DECIMAL(18,4) DEFAULT 0,
  rate                                DECIMAL(18,4) DEFAULT 0,
  discount                            DECIMAL(18,4) DEFAULT 0,
  discount_amount                     DECIMAL(18,4) DEFAULT 0,
  item_total                          DECIMAL(18,4) DEFAULT 0,
  item_total_inclusive_of_tax         DECIMAL(18,4) DEFAULT 0,
  tax_id                              VARCHAR(100) NULL,
  tax_name                            VARCHAR(255) NULL,
  tax_type                            VARCHAR(64)  NULL,
  tax_percentage                      DECIMAL(7,4) NULL,
  tax_amount                          DECIMAL(18,4) DEFAULT 0,
  is_invoiced                         TINYINT(1)   DEFAULT 1,
  project_id                          VARCHAR(100) NULL,
  expense_id                          VARCHAR(100) NULL,
  time_entry_ids_json                 JSON         NULL,
  salesorder_item_id                  VARCHAR(100) NULL,
  warehouse_id                        VARCHAR(100) NULL,
  warehouse_name                      VARCHAR(255) NULL,
  custom_fields_json                  JSON         NULL,
  UNIQUE KEY uq_zbil (user_id, org_id, zoho_line_item_id),
  INDEX idx_zbil_inv  (zoho_invoice_id),
  INDEX idx_zbil_item (zoho_item_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_recurring_invoices (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_recurring_invoice_id       VARCHAR(100) NOT NULL,
  recurrence_name                 VARCHAR(255) NULL,
  reference_number                VARCHAR(100) NULL,
  status                          VARCHAR(50)  NULL,
  zoho_customer_id                VARCHAR(100) NULL,
  customer_name                   VARCHAR(255) NULL,
  recurrence_frequency            VARCHAR(50)  NULL,
  repeat_every                    INT          DEFAULT 1,
  start_date                      DATE         NULL,
  end_date                        DATE         NULL,
  next_invoice_date               DATE         NULL,
  last_sent_date                  DATE         NULL,
  total                           DECIMAL(18,4) DEFAULT 0,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_total                       DECIMAL(18,4) DEFAULT 0,
  discount                        DECIMAL(18,4) DEFAULT 0,
  adjustment                      DECIMAL(18,4) DEFAULT 0,
  shipping_charge                 DECIMAL(18,4) DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  is_inclusive_tax                TINYINT(1)   DEFAULT 0,
  template_id                     VARCHAR(100) NULL,
  payment_terms                   INT          DEFAULT 0,
  payment_terms_label             VARCHAR(64)  NULL,
  notes                           TEXT         NULL,
  terms                           TEXT         NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_rinv (user_id, org_id, zoho_recurring_invoice_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_customer_payments (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_payment_id                 VARCHAR(100) NOT NULL,
  payment_number                  VARCHAR(100) NULL,
  payment_number_prefix           VARCHAR(50)  NULL,
  payment_number_suffix           VARCHAR(50)  NULL,
  zoho_customer_id                VARCHAR(100) NULL,
  customer_name                   VARCHAR(255) NULL,
  email                           VARCHAR(255) NULL,
  date                            DATE         NULL,
  amount                          DECIMAL(18,4) DEFAULT 0,
  amount_bcy                      DECIMAL(18,4) DEFAULT 0,
  unused_amount                   DECIMAL(18,4) DEFAULT 0,
  unused_amount_bcy               DECIMAL(18,4) DEFAULT 0,
  bank_charges                    DECIMAL(18,4) DEFAULT 0,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  payment_mode                    VARCHAR(50)  NULL,
  description                     TEXT         NULL,
  reference_number                VARCHAR(100) NULL,
  account_id                      VARCHAR(100) NULL,
  account_name                    VARCHAR(255) NULL,
  account_type                    VARCHAR(50)  NULL,
  tax_account_id                  VARCHAR(100) NULL,
  tds_amount_withheld             DECIMAL(18,4) DEFAULT 0,
  tax_amount_withheld             DECIMAL(18,4) DEFAULT 0,
  is_pre_gst                      TINYINT(1)   DEFAULT 0,
  is_paid_via_print_check         TINYINT(1)   DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  currency_symbol                 VARCHAR(10)  NULL,
  status                          VARCHAR(50)  NULL,
  gateway_transaction_id          VARCHAR(100) NULL,
  card_type                       VARCHAR(50)  NULL,
  has_attachment                  TINYINT(1)   DEFAULT 0,
  documents_count                 INT          DEFAULT 0,
  online_transaction_id           VARCHAR(100) NULL,
  online_transaction_payment_link VARCHAR(255) NULL,
  invoice_numbers                 VARCHAR(1000) NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_cpay (user_id, org_id, zoho_payment_id),
  INDEX idx_zbcp_cust (zoho_customer_id),
  INDEX idx_zbcp_date (date),
  INDEX idx_zbcp_mode (payment_mode),
  INDEX idx_zbcp_mod  (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_customer_payment_invoices (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_payment_id             VARCHAR(100) NOT NULL,
  zoho_invoice_id             VARCHAR(100) NOT NULL,
  invoice_number              VARCHAR(100) NULL,
  invoice_date                DATE         NULL,
  invoice_amount              DECIMAL(18,4) DEFAULT 0,
  amount_applied              DECIMAL(18,4) DEFAULT 0,
  tax_amount_withheld         DECIMAL(18,4) DEFAULT 0,
  apply_date                  DATE         NULL,
  UNIQUE KEY uq_zbcpi (user_id, org_id, zoho_payment_id, zoho_invoice_id),
  INDEX idx_zbcpi_pay (zoho_payment_id),
  INDEX idx_zbcpi_inv (zoho_invoice_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_credit_notes (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_creditnote_id              VARCHAR(100) NOT NULL,
  creditnote_number               VARCHAR(100) NULL,
  reference_number                VARCHAR(100) NULL,
  status                          VARCHAR(50)  NULL,
  zoho_customer_id                VARCHAR(100) NULL,
  customer_name                   VARCHAR(255) NULL,
  email                           VARCHAR(255) NULL,
  date                            DATE         NULL,
  reason                          VARCHAR(255) NULL,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_total                       DECIMAL(18,4) DEFAULT 0,
  discount                        DECIMAL(18,4) DEFAULT 0,
  discount_amount                 DECIMAL(18,4) DEFAULT 0,
  total                           DECIMAL(18,4) DEFAULT 0,
  total_bcy                       DECIMAL(18,4) DEFAULT 0,
  balance                         DECIMAL(18,4) DEFAULT 0,
  balance_bcy                     DECIMAL(18,4) DEFAULT 0,
  credits_applied                 DECIMAL(18,4) DEFAULT 0,
  refunded_amount                 DECIMAL(18,4) DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  is_inclusive_tax                TINYINT(1)   DEFAULT 0,
  is_pre_gst                      TINYINT(1)   DEFAULT 0,
  gst_no                          VARCHAR(20)  NULL,
  gst_treatment                   VARCHAR(50)  NULL,
  place_of_supply                 VARCHAR(100) NULL,
  template_id                     VARCHAR(100) NULL,
  notes                           TEXT         NULL,
  terms                           TEXT         NULL,
  billing_address_json            JSON         NULL,
  shipping_address_json           JSON         NULL,
  documents_count                 INT          DEFAULT 0,
  invoice_id                      VARCHAR(100) NULL,
  invoice_number                  VARCHAR(100) NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_cn (user_id, org_id, zoho_creditnote_id),
  INDEX idx_zbcn_cust   (zoho_customer_id),
  INDEX idx_zbcn_status (status),
  INDEX idx_zbcn_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A credit note is a negative sale, and Zoho's Tax Summary reports it at the
-- same per-rate granularity as an invoice. That breakdown exists only on the
-- line items, so they are warehoused exactly like zb_invoice_line_items.
CREATE TABLE IF NOT EXISTS zb_credit_note_line_items (
  id                                  INT AUTO_INCREMENT PRIMARY KEY,
  user_id                             INT          NOT NULL,
  org_id                              VARCHAR(100) NOT NULL,
  zoho_line_item_id                   VARCHAR(100) NOT NULL,
  zoho_creditnote_id                  VARCHAR(100) NOT NULL,
  line_position                       INT          DEFAULT 0,
  zoho_item_id                        VARCHAR(100) NULL,
  item_name                           VARCHAR(255) NULL,
  description                         TEXT         NULL,
  unit                                VARCHAR(50)  NULL,
  hsn_or_sac                          VARCHAR(50)  NULL,
  account_id                          VARCHAR(100) NULL,
  account_name                        VARCHAR(255) NULL,
  quantity                            DECIMAL(18,4) DEFAULT 0,
  rate                                DECIMAL(18,4) DEFAULT 0,
  discount                            DECIMAL(18,4) DEFAULT 0,
  discount_amount                     DECIMAL(18,4) DEFAULT 0,
  item_total                          DECIMAL(18,4) DEFAULT 0,
  item_total_inclusive_of_tax         DECIMAL(18,4) DEFAULT 0,
  tax_id                              VARCHAR(100) NULL,
  tax_name                            VARCHAR(255) NULL,
  tax_type                            VARCHAR(64)  NULL,
  tax_percentage                      DECIMAL(7,4) NULL,
  tax_amount                          DECIMAL(18,4) DEFAULT 0,
  project_id                          VARCHAR(100) NULL,
  custom_fields_json                  JSON         NULL,
  UNIQUE KEY uq_zbcnli (user_id, org_id, zoho_line_item_id),
  INDEX idx_zbcnli_cn   (zoho_creditnote_id),
  INDEX idx_zbcnli_item (zoho_item_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_credit_note_invoices (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_creditnote_id          VARCHAR(100) NOT NULL,
  zoho_invoice_id             VARCHAR(100) NOT NULL,
  invoice_number              VARCHAR(100) NULL,
  amount_applied              DECIMAL(18,4) DEFAULT 0,
  apply_date                  DATE         NULL,
  UNIQUE KEY uq_zbcni (user_id, org_id, zoho_creditnote_id, zoho_invoice_id),
  INDEX idx_zbcni_cn  (zoho_creditnote_id),
  INDEX idx_zbcni_inv (zoho_invoice_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ════════════════════════════════════════════════════════════════════════════
--  SILVER — purchase-side (PO, Bills, Vendor Payments, Vendor Credits)
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS zb_purchase_orders (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_purchaseorder_id           VARCHAR(100) NOT NULL,
  purchaseorder_number            VARCHAR(100) NULL,
  reference_number                VARCHAR(100) NULL,
  status                          VARCHAR(50)  NULL,
  order_status                    VARCHAR(50)  NULL,
  billed_status                   VARCHAR(50)  NULL,
  zoho_vendor_id                  VARCHAR(100) NULL,
  vendor_name                     VARCHAR(255) NULL,
  date                            DATE         NULL,
  delivery_date                   DATE         NULL,
  expected_delivery_date          DATE         NULL,
  is_drop_shipment                TINYINT(1)   DEFAULT 0,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_total                       DECIMAL(18,4) DEFAULT 0,
  discount                        DECIMAL(18,4) DEFAULT 0,
  shipping_charge                 DECIMAL(18,4) DEFAULT 0,
  adjustment                      DECIMAL(18,4) DEFAULT 0,
  total                           DECIMAL(18,4) DEFAULT 0,
  total_bcy                       DECIMAL(18,4) DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  is_inclusive_tax                TINYINT(1)   DEFAULT 0,
  is_pre_gst                      TINYINT(1)   DEFAULT 0,
  gst_treatment                   VARCHAR(50)  NULL,
  place_of_supply                 VARCHAR(100) NULL,
  template_id                     VARCHAR(100) NULL,
  notes                           TEXT         NULL,
  terms                           TEXT         NULL,
  billing_address_json            JSON         NULL,
  shipping_address_json           JSON         NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_po (user_id, org_id, zoho_purchaseorder_id),
  INDEX idx_zbpo_vendor (zoho_vendor_id),
  INDEX idx_zbpo_status (status),
  INDEX idx_zbpo_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_bills (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_bill_id                    VARCHAR(100) NOT NULL,
  bill_number                     VARCHAR(100) NULL,
  reference_number                VARCHAR(100) NULL,
  status                          VARCHAR(50)  NULL,
  zoho_vendor_id                  VARCHAR(100) NULL,
  vendor_name                     VARCHAR(255) NULL,
  zoho_purchaseorder_id           VARCHAR(100) NULL,
  zoho_recurring_bill_id          VARCHAR(100) NULL,
  date                            DATE         NULL,
  due_date                        DATE         NULL,
  due_in_days                     VARCHAR(50)  NULL,
  due_by_days                     INT          NULL,
  payment_terms                   INT          DEFAULT 0,
  payment_terms_label             VARCHAR(64)  NULL,
  payment_expected_date           DATE         NULL,
  last_payment_date               DATE         NULL,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_total                       DECIMAL(18,4) DEFAULT 0,
  discount                        DECIMAL(18,4) DEFAULT 0,
  discount_amount                 DECIMAL(18,4) DEFAULT 0,
  discount_type                   VARCHAR(20)  NULL,
  is_discount_before_tax          TINYINT(1)   DEFAULT 1,
  adjustment                      DECIMAL(18,4) DEFAULT 0,
  adjustment_description          VARCHAR(255) NULL,
  total                           DECIMAL(18,4) DEFAULT 0,
  total_bcy                       DECIMAL(18,4) DEFAULT 0,
  balance                         DECIMAL(18,4) DEFAULT 0,
  balance_bcy                     DECIMAL(18,4) DEFAULT 0,
  payment_made                    DECIMAL(18,4) DEFAULT 0,
  vendor_credits_applied          DECIMAL(18,4) DEFAULT 0,
  is_inclusive_tax                TINYINT(1)   DEFAULT 0,
  is_reverse_charge_applied       TINYINT(1)   DEFAULT 0,
  is_pre_gst                      TINYINT(1)   DEFAULT 0,
  is_tds_applied                  TINYINT(1)   DEFAULT 0,
  tds_amount_withheld             DECIMAL(18,4) DEFAULT 0,
  gst_no                          VARCHAR(20)  NULL,
  gst_treatment                   VARCHAR(50)  NULL,
  place_of_supply                 VARCHAR(100) NULL,
  source_of_supply                VARCHAR(100) NULL,
  destination_of_supply           VARCHAR(100) NULL,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  currency_symbol                 VARCHAR(10)  NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  attention                       VARCHAR(255) NULL,
  email                           VARCHAR(255) NULL,
  notes                           TEXT         NULL,
  terms                           TEXT         NULL,
  attachment_name                 VARCHAR(255) NULL,
  documents_count                 INT          DEFAULT 0,
  billing_address_json            JSON         NULL,
  template_id                     VARCHAR(100) NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  deleted_at                      TIMESTAMP    NULL,
  UNIQUE KEY uq_zb_bill (user_id, org_id, zoho_bill_id),
  INDEX idx_zbb_vendor (zoho_vendor_id),
  INDEX idx_zbb_status (status),
  INDEX idx_zbb_date   (date),
  INDEX idx_zbb_due    (due_date),
  INDEX idx_zbb_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_bill_line_items (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_line_item_id           VARCHAR(100) NOT NULL,
  zoho_bill_id                VARCHAR(100) NOT NULL,
  line_position               INT          DEFAULT 0,
  zoho_item_id                VARCHAR(100) NULL,
  item_name                   VARCHAR(255) NULL,
  description                 TEXT         NULL,
  account_id                  VARCHAR(100) NULL,
  account_name                VARCHAR(255) NULL,
  customer_id                 VARCHAR(100) NULL,
  customer_name               VARCHAR(255) NULL,
  project_id                  VARCHAR(100) NULL,
  project_name                VARCHAR(255) NULL,
  is_billable                 TINYINT(1)   DEFAULT 0,
  quantity                    DECIMAL(18,4) DEFAULT 0,
  unit                        VARCHAR(50)  NULL,
  rate                        DECIMAL(18,4) DEFAULT 0,
  discount                    DECIMAL(18,4) DEFAULT 0,
  discount_amount             DECIMAL(18,4) DEFAULT 0,
  item_total                  DECIMAL(18,4) DEFAULT 0,
  item_total_inclusive_of_tax DECIMAL(18,4) DEFAULT 0,
  tax_id                      VARCHAR(100) NULL,
  tax_name                    VARCHAR(255) NULL,
  tax_percentage              DECIMAL(7,4) NULL,
  tax_amount                  DECIMAL(18,4) DEFAULT 0,
  reverse_charge_tax_id       VARCHAR(100) NULL,
  reverse_charge_tax_amount   DECIMAL(18,4) DEFAULT 0,
  hsn_or_sac                  VARCHAR(50)  NULL,
  itc_eligibility             VARCHAR(50)  NULL,
  custom_fields_json          JSON         NULL,
  UNIQUE KEY uq_zbbl (user_id, org_id, zoho_line_item_id),
  INDEX idx_zbbl_bill (zoho_bill_id),
  INDEX idx_zbbl_item (zoho_item_id),
  INDEX idx_zbbl_acct (account_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_recurring_bills (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_recurring_bill_id          VARCHAR(100) NOT NULL,
  recurrence_name                 VARCHAR(255) NULL,
  status                          VARCHAR(50)  NULL,
  zoho_vendor_id                  VARCHAR(100) NULL,
  vendor_name                     VARCHAR(255) NULL,
  recurrence_frequency            VARCHAR(50)  NULL,
  repeat_every                    INT          DEFAULT 1,
  start_date                      DATE         NULL,
  end_date                        DATE         NULL,
  next_bill_date                  DATE         NULL,
  last_created_date               DATE         NULL,
  total                           DECIMAL(18,4) DEFAULT 0,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_total                       DECIMAL(18,4) DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  payment_terms                   INT          DEFAULT 0,
  payment_terms_label             VARCHAR(64)  NULL,
  notes                           TEXT         NULL,
  terms                           TEXT         NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_rbill (user_id, org_id, zoho_recurring_bill_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_vendor_payments (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_vendor_payment_id          VARCHAR(100) NOT NULL,
  payment_number                  VARCHAR(100) NULL,
  zoho_vendor_id                  VARCHAR(100) NULL,
  vendor_name                     VARCHAR(255) NULL,
  date                            DATE         NULL,
  amount                          DECIMAL(18,4) DEFAULT 0,
  amount_bcy                      DECIMAL(18,4) DEFAULT 0,
  unused_amount                   DECIMAL(18,4) DEFAULT 0,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  payment_mode                    VARCHAR(50)  NULL,
  description                     TEXT         NULL,
  reference_number                VARCHAR(100) NULL,
  account_id                      VARCHAR(100) NULL,
  account_name                    VARCHAR(255) NULL,
  paid_through_account_id         VARCHAR(100) NULL,
  paid_through_account_name       VARCHAR(255) NULL,
  is_paid_via_print_check         TINYINT(1)   DEFAULT 0,
  is_paid_via_online_payment      TINYINT(1)   DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  status                          VARCHAR(50)  NULL,
  check_details_json              JSON         NULL,
  tds_tax_id                      VARCHAR(100) NULL,
  tds_amount                      DECIMAL(18,4) DEFAULT 0,
  has_attachment                  TINYINT(1)   DEFAULT 0,
  documents_count                 INT          DEFAULT 0,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_vpay (user_id, org_id, zoho_vendor_payment_id),
  INDEX idx_zbvp_vendor (zoho_vendor_id),
  INDEX idx_zbvp_date   (date),
  INDEX idx_zbvp_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_vendor_payment_bills (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_vendor_payment_id      VARCHAR(100) NOT NULL,
  zoho_bill_id                VARCHAR(100) NOT NULL,
  bill_number                 VARCHAR(100) NULL,
  bill_date                   DATE         NULL,
  bill_amount                 DECIMAL(18,4) DEFAULT 0,
  amount_applied              DECIMAL(18,4) DEFAULT 0,
  apply_date                  DATE         NULL,
  UNIQUE KEY uq_zbvpb (user_id, org_id, zoho_vendor_payment_id, zoho_bill_id),
  INDEX idx_zbvpb_vp   (zoho_vendor_payment_id),
  INDEX idx_zbvpb_bill (zoho_bill_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_vendor_credits (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_vendor_credit_id           VARCHAR(100) NOT NULL,
  vendor_credit_number            VARCHAR(100) NULL,
  reference_number                VARCHAR(100) NULL,
  status                          VARCHAR(50)  NULL,
  zoho_vendor_id                  VARCHAR(100) NULL,
  vendor_name                     VARCHAR(255) NULL,
  zoho_purchaseorder_id           VARCHAR(100) NULL,
  date                            DATE         NULL,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_total                       DECIMAL(18,4) DEFAULT 0,
  total                           DECIMAL(18,4) DEFAULT 0,
  total_bcy                       DECIMAL(18,4) DEFAULT 0,
  balance                         DECIMAL(18,4) DEFAULT 0,
  credits_applied                 DECIMAL(18,4) DEFAULT 0,
  refunded_amount                 DECIMAL(18,4) DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  is_inclusive_tax                TINYINT(1)   DEFAULT 0,
  is_pre_gst                      TINYINT(1)   DEFAULT 0,
  gst_no                          VARCHAR(20)  NULL,
  gst_treatment                   VARCHAR(50)  NULL,
  place_of_supply                 VARCHAR(100) NULL,
  notes                           TEXT         NULL,
  terms                           TEXT         NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_vc (user_id, org_id, zoho_vendor_credit_id),
  INDEX idx_zbvc_vendor (zoho_vendor_id),
  INDEX idx_zbvc_status (status),
  INDEX idx_zbvc_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ════════════════════════════════════════════════════════════════════════════
--  SILVER — expenses, journals, bank, documents
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS zb_expenses (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_expense_id                 VARCHAR(100) NOT NULL,
  expense_type                    VARCHAR(50)  NULL,
  date                            DATE         NULL,
  status                          VARCHAR(50)  NULL,
  account_id                      VARCHAR(100) NULL,
  account_name                    VARCHAR(255) NULL,
  paid_through_account_id         VARCHAR(100) NULL,
  paid_through_account_name       VARCHAR(255) NULL,
  zoho_vendor_id                  VARCHAR(100) NULL,
  vendor_name                     VARCHAR(255) NULL,
  zoho_customer_id                VARCHAR(100) NULL,
  customer_name                   VARCHAR(255) NULL,
  amount                          DECIMAL(18,4) DEFAULT 0,
  bcy_amount                      DECIMAL(18,4) DEFAULT 0,
  bcy_total                       DECIMAL(18,4) DEFAULT 0,
  total                           DECIMAL(18,4) DEFAULT 0,
  total_without_tax               DECIMAL(18,4) DEFAULT 0,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_amount                      DECIMAL(18,4) DEFAULT 0,
  reverse_charge_tax_amount       DECIMAL(18,4) DEFAULT 0,
  tax_id                          VARCHAR(100) NULL,
  tax_name                        VARCHAR(255) NULL,
  tax_percentage                  DECIMAL(7,4) NULL,
  is_inclusive_tax                TINYINT(1)   DEFAULT 0,
  is_personal                     TINYINT(1)   DEFAULT 0,
  is_billable                     TINYINT(1)   DEFAULT 0,
  is_reimbursable                 TINYINT(1)   DEFAULT 0,
  reimbursable_amount             DECIMAL(18,4) DEFAULT 0,
  invoice_id                      VARCHAR(100) NULL,
  invoice_number                  VARCHAR(100) NULL,
  invoice_status                  VARCHAR(50)  NULL,
  project_id                      VARCHAR(100) NULL,
  project_name                    VARCHAR(255) NULL,
  expense_receipt_name            VARCHAR(255) NULL,
  expense_receipt_type            VARCHAR(50)  NULL,
  has_attachment                  TINYINT(1)   DEFAULT 0,
  documents_count                 INT          DEFAULT 0,
  description                     TEXT         NULL,
  notes                           TEXT         NULL,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  reference_number                VARCHAR(100) NULL,
  recurring_expense_id            VARCHAR(100) NULL,
  is_pre_gst                      TINYINT(1)   DEFAULT 0,
  gst_no                          VARCHAR(20)  NULL,
  gst_treatment                   VARCHAR(50)  NULL,
  destination_of_supply           VARCHAR(100) NULL,
  source_of_supply                VARCHAR(100) NULL,
  hsn_or_sac                      VARCHAR(50)  NULL,
  mileage_rate                    DECIMAL(18,4) NULL,
  mileage_unit                    VARCHAR(20)  NULL,
  mileage_type                    VARCHAR(20)  NULL,
  start_reading                   DECIMAL(18,4) NULL,
  end_reading                     DECIMAL(18,4) NULL,
  vehicle_type                    VARCHAR(50)  NULL,
  itc_eligibility                 VARCHAR(50)  NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  deleted_at                      TIMESTAMP    NULL,
  UNIQUE KEY uq_zb_exp (user_id, org_id, zoho_expense_id),
  INDEX idx_zbe_acct   (account_id),
  INDEX idx_zbe_date   (date),
  INDEX idx_zbe_vendor (zoho_vendor_id),
  INDEX idx_zbe_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_expense_line_items (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_line_item_id           VARCHAR(100) NOT NULL,
  zoho_expense_id             VARCHAR(100) NOT NULL,
  line_position               INT          DEFAULT 0,
  account_id                  VARCHAR(100) NULL,
  account_name                VARCHAR(255) NULL,
  amount                      DECIMAL(18,4) DEFAULT 0,
  description                 TEXT         NULL,
  tax_id                      VARCHAR(100) NULL,
  tax_percentage              DECIMAL(7,4) NULL,
  tax_amount                  DECIMAL(18,4) DEFAULT 0,
  customer_id                 VARCHAR(100) NULL,
  project_id                  VARCHAR(100) NULL,
  is_billable                 TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zbel (user_id, org_id, zoho_line_item_id),
  INDEX idx_zbel_exp (zoho_expense_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_recurring_expenses (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_recurring_expense_id       VARCHAR(100) NOT NULL,
  recurrence_name                 VARCHAR(255) NULL,
  status                          VARCHAR(50)  NULL,
  account_id                      VARCHAR(100) NULL,
  account_name                    VARCHAR(255) NULL,
  zoho_vendor_id                  VARCHAR(100) NULL,
  vendor_name                     VARCHAR(255) NULL,
  recurrence_frequency            VARCHAR(50)  NULL,
  repeat_every                    INT          DEFAULT 1,
  start_date                      DATE         NULL,
  end_date                        DATE         NULL,
  next_expense_date               DATE         NULL,
  last_created_date               DATE         NULL,
  total                           DECIMAL(18,4) DEFAULT 0,
  sub_total                       DECIMAL(18,4) DEFAULT 0,
  tax_total                       DECIMAL(18,4) DEFAULT 0,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  description                     TEXT         NULL,
  custom_fields_json              JSON         NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_rexp (user_id, org_id, zoho_recurring_expense_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_journals (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_journal_id                 VARCHAR(100) NOT NULL,
  journal_number                  VARCHAR(100) NULL,
  reference_number                VARCHAR(100) NULL,
  journal_date                    DATE         NULL,
  journal_type                    VARCHAR(50)  NULL,
  status                          VARCHAR(50)  NULL,
  notes                           TEXT         NULL,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  currency_symbol                 VARCHAR(10)  NULL,
  exchange_rate                   DECIMAL(18,8) DEFAULT 1.0,
  total                           DECIMAL(18,4) DEFAULT 0,
  total_debit                     DECIMAL(18,4) DEFAULT 0,
  total_credit                    DECIMAL(18,4) DEFAULT 0,
  total_bcy                       DECIMAL(18,4) DEFAULT 0,
  include_in_vat_return           TINYINT(1)   DEFAULT 0,
  is_inclusive_tax                TINYINT(1)   DEFAULT 0,
  product_type                    VARCHAR(50)  NULL,
  custom_fields_json              JSON         NULL,
  documents_count                 INT          DEFAULT 0,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_journal (user_id, org_id, zoho_journal_id),
  INDEX idx_zbj_date   (journal_date),
  INDEX idx_zbj_status (status),
  INDEX idx_zbj_mod    (user_id, org_id, zoho_last_modified_time),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_journal_line_items (
  id                          INT AUTO_INCREMENT PRIMARY KEY,
  user_id                     INT          NOT NULL,
  org_id                      VARCHAR(100) NOT NULL,
  zoho_line_item_id           VARCHAR(100) NOT NULL,
  zoho_journal_id             VARCHAR(100) NOT NULL,
  line_position               INT          DEFAULT 0,
  account_id                  VARCHAR(100) NOT NULL,
  account_name                VARCHAR(255) NULL,
  account_type                VARCHAR(50)  NULL,
  description                 TEXT         NULL,
  debit_or_credit             VARCHAR(10)  NOT NULL,
  amount                      DECIMAL(18,4) DEFAULT 0,
  amount_bcy                  DECIMAL(18,4) DEFAULT 0,
  tax_id                      VARCHAR(100) NULL,
  tax_amount                  DECIMAL(18,4) DEFAULT 0,
  customer_id                 VARCHAR(100) NULL,
  customer_name               VARCHAR(255) NULL,
  vendor_id                   VARCHAR(100) NULL,
  vendor_name                 VARCHAR(255) NULL,
  project_id                  VARCHAR(100) NULL,
  contact_id                  VARCHAR(100) NULL,
  UNIQUE KEY uq_zbjl (user_id, org_id, zoho_line_item_id),
  INDEX idx_zbjl_journal (zoho_journal_id),
  INDEX idx_zbjl_account (account_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zb_bank_accounts (
  id                              INT AUTO_INCREMENT PRIMARY KEY,
  user_id                         INT          NOT NULL,
  org_id                          VARCHAR(100) NOT NULL,
  zoho_account_id                 VARCHAR(100) NOT NULL,
  account_name                    VARCHAR(255) NULL,
  account_code                    VARCHAR(64)  NULL,
  account_number                  VARCHAR(64)  NULL,
  account_type                    VARCHAR(50)  NULL,
  bank_name                       VARCHAR(255) NULL,
  routing_number                  VARCHAR(50)  NULL,
  swift_code                      VARCHAR(50)  NULL,
  bank_address                    TEXT         NULL,
  description                     TEXT         NULL,
  currency_id                     VARCHAR(100) NULL,
  currency_code                   VARCHAR(3)   NULL,
  bcy_account_balance             DECIMAL(18,4) DEFAULT 0,
  account_balance                 DECIMAL(18,4) DEFAULT 0,
  uncategorized_transactions      INT          DEFAULT 0,
  is_primary_account              TINYINT(1)   DEFAULT 0,
  is_paypal_account               TINYINT(1)   DEFAULT 0,
  is_active                       TINYINT(1)   DEFAULT 1,
  is_feeds_active                 TINYINT(1)   DEFAULT 0,
  paypal_email_address            VARCHAR(255) NULL,
  last_feed_status                VARCHAR(50)  NULL,
  last_feed_date                  DATETIME     NULL,
  feed_aggregator_name            VARCHAR(100) NULL,
  zoho_created_time               DATETIME     NULL,
  zoho_last_modified_time         DATETIME     NULL,
  synced_at                       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  raw_payload_id                  BIGINT       NULL,
  is_deleted                      TINYINT(1)   DEFAULT 0,
  UNIQUE KEY uq_zb_bank (user_id, org_id, zoho_account_id),
  INDEX idx_zbba_type (account_type),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- NOTE: `zb_bank_transactions` was removed. Bank transactions are stored in the
-- legacy `bank_transactions` table (written by zohoService, read by reports/dashboard).
